USE BankingManagementDB;
GO

-- CUSTOMER
CREATE INDEX IX_CUSTOMER_FullName
ON dbo.CUSTOMER(FullName);
GO
CREATE INDEX IX_CUSTOMER_NationalID
ON dbo.CUSTOMER(NationalID);
GO
CREATE INDEX IX_CUSTOMER_Phone
ON dbo.CUSTOMER(Phone);
GO
CREATE INDEX IX_CUSTOMER_CustomerType_Status
ON dbo.CUSTOMER(CustomerType, [Status]);
GO
-- EMPLOYEE
CREATE INDEX IX_EMPLOYEE_BranchID
ON dbo.EMPLOYEE(BranchID);
GO
CREATE INDEX IX_EMPLOYEE_RoleID
ON dbo.EMPLOYEE(RoleID);
GO
CREATE INDEX IX_EMPLOYEE_Status
ON dbo.EMPLOYEE([Status]);
GO
-- BANK_ACCOUNT
CREATE INDEX IX_BANK_ACCOUNT_CustomerID
ON dbo.BANK_ACCOUNT(CustomerID);
GO
CREATE INDEX IX_BANK_ACCOUNT_BranchID
ON dbo.BANK_ACCOUNT(BranchID);
GO
CREATE INDEX IX_BANK_ACCOUNT_AccountTypeID
ON dbo.BANK_ACCOUNT(AccountTypeID);
GO
CREATE INDEX IX_BANK_ACCOUNT_Status
ON dbo.BANK_ACCOUNT([Status]);
GO
CREATE INDEX IX_BANK_ACCOUNT_Customer_Status
ON dbo.BANK_ACCOUNT(CustomerID, [Status]);
GO
-- CARD
CREATE INDEX IX_CARD_AccountID
ON dbo.CARD(AccountID);
GO
CREATE INDEX IX_CARD_Status
ON dbo.CARD([Status]);
GO
-- ACCOUNT_STATUS_HISTORY
CREATE INDEX IX_ACCOUNT_STATUS_HISTORY_AccountID_ChangedDate
ON dbo.ACCOUNT_STATUS_HISTORY(AccountID, ChangedDate DESC);
GO
-- BANK_TRANSACTION
CREATE INDEX IX_BANK_TRANSACTION_TransactionDate
ON dbo.BANK_TRANSACTION(TransactionDate);
GO
CREATE INDEX IX_BANK_TRANSACTION_SourceAccountID
ON dbo.BANK_TRANSACTION(SourceAccountID);
GO
CREATE INDEX IX_BANK_TRANSACTION_DestinationAccountID
ON dbo.BANK_TRANSACTION(DestinationAccountID);
GO
CREATE INDEX IX_BANK_TRANSACTION_EmployeeID
ON dbo.BANK_TRANSACTION(EmployeeID);
GO
CREATE INDEX IX_BANK_TRANSACTION_TransactionTypeID
ON dbo.BANK_TRANSACTION(TransactionTypeID);
GO
CREATE INDEX IX_BANK_TRANSACTION_Channel_Status
ON dbo.BANK_TRANSACTION(Channel, [Status]);
GO
CREATE INDEX IX_BANK_TRANSACTION_SourceAccountID_TransactionDate
ON dbo.BANK_TRANSACTION(SourceAccountID, TransactionDate DESC);
GO
CREATE INDEX IX_BANK_TRANSACTION_DestinationAccountID_TransactionDate
ON dbo.BANK_TRANSACTION(DestinationAccountID, TransactionDate DESC);
GO
-- LOAN
CREATE INDEX IX_LOAN_CustomerID
ON dbo.LOAN(CustomerID);
GO
CREATE INDEX IX_LOAN_BranchID
ON dbo.LOAN(BranchID);
GO
CREATE INDEX IX_LOAN_EmployeeID
ON dbo.LOAN(EmployeeID);
GO
CREATE INDEX IX_LOAN_LoanTypeID
ON dbo.LOAN(LoanTypeID);
GO
CREATE INDEX IX_LOAN_Status
ON dbo.LOAN([Status]);
GO
CREATE INDEX IX_LOAN_CustomerID_Status
ON dbo.LOAN(CustomerID, [Status]);
GO
-- LOAN_PAYMENT
CREATE INDEX IX_LOAN_PAYMENT_LoanID
ON dbo.LOAN_PAYMENT(LoanID);
GO
CREATE INDEX IX_LOAN_PAYMENT_PaymentDate
ON dbo.LOAN_PAYMENT(PaymentDate);
GO
CREATE INDEX IX_LOAN_PAYMENT_LoanID_PaymentDate
ON dbo.LOAN_PAYMENT(LoanID, PaymentDate DESC);
GO